### ISSUE TITLE
How to use "v-once" directive in JSX?

### ISSUE THREAD

**Issue by funny-family** [vuejs/babel-plugin-jsx#535]
### 🧐 Problem Description
Do not understand how to use "v-once" directive with jsx?

### 💻 Sample code

```
...
<div v-once>render once or not....</div>
...
```

### 🚑 Other information
When I try apply this directive I get error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deep')
    at withDirectives (runtime-core.esm-bundler.js?5c40:3019)
```

**Comment by CrownHanhard** [comment]
You can try this
```html
<div onClickOnce = { your event }> content </div>
```

**Comment by funny-family** [comment]
@CrownHanhard `onClickOnce` allows me to click on `div` once, but not render render it only once and no more.

**Comment by CrownHanhard** [comment]
Maybe like v-if, you can only do it in other ways For example, set a Watcheror initialize deep copy data

**Comment by funny-family** [comment]
@CrownHanhard, I don't think that it work in that way, because:

this
```html
<div v-once>
  addadada
</div>
```

compiels into this:
```javascript
import { setBlockTracking as _setBlockTracking, createTextVNode as _createTextVNode, createElementVNode as _createElementVNode } from "vue"

export function render(_ctx, _cache, $props, $setup, $data, $options) {
  return _cache[0] || (
    _setBlockTracking(-1),
    _cache[0] = _createElementVNode("div", null, [
      _createTextVNode(" addadada ")
    ]),
    _setBlockTracking(1),
    _cache[0]
  )
}
```

See [here](https://vue-next-template-explorer.netlify.app/#eyJzcmMiOiI8ZGl2IHYtb25jZT5cbiAgYWRkYWRhZGFcbjwvZGl2PlxuIiwib3B0aW9ucyI6e319).

**Comment by CrownHanhard** [comment]
Yes, you are right! I found instructions such as: v-show, v-slots,html , text, model , models, etc. in the code, but I didn't find the instruction v-once. Look at [this](https://github.com/vuejs/babel-plugin-jsx/blob/dev/packages/babel-plugin-jsx/src/parseDirectives.ts) and [this](https://github.com/vuejs/babel-plugin-jsx/blob/dev/packages/babel-plugin-jsx/src/transform-vue-jsx.ts) .It's all on line 142

**Comment by funny-family** [comment]
🤔

**Comment by funny-family** [comment]
Solution was right above me. Big bruh xD

```javascript
import { setBlockTracking as _setBlockTracking, createTextVNode as _createTextVNode, createElementVNode as _createElementVNode } from "vue"

export function render(_ctx, _cache, $props, $setup, $data, $options) {
  return _cache[0] || (
    _setBlockTracking(-1),
    _cache[0] = _createElementVNode("div", null, [
      _createTextVNode(" addadada ")
    ]),
    _setBlockTracking(1),
    _cache[0]
  )
}
```

**Comment by tcastelly** [comment]
Maybe it can help someone :)

The first parameter of the `withMemo` is the trigger. Here because the array is empty it's like a `v-once`.

```typescript
import { defineComponent, ExtractPropTypes, withMemo } from 'vue';

const props = {
  msg: String,
} as const;

export default defineComponent({
  name: 'DisplayMsg',
  props,
  render(ctx: ExtractPropTypes<typeof props>, cache: unknown[]) {
    return withMemo([/* ctx.msg */], () => <h1>{ctx.msg}</h1>, cache, 0);
  },
});
```

**Comment by funny-family** [comment]
> Maybe it can help someone :)
> 
> The first parameter of the `withMemo` is the trigger. Here because the array is empty it's like a `v-once`.
> 
> ```ts
> import { defineComponent, ExtractPropTypes, withMemo } from 'vue';
> 
> const props = {
>   msg: String,
> } as const;
> 
> export default defineComponent({
>   name: 'DisplayMsg',
>   props,
>   render(ctx: ExtractPropTypes<typeof props>, cache: unknown[]) {
>     return withMemo([/* ctx.msg */], () => <h1>{ctx.msg}</h1>, cache, 0);
>   },
> });
> ```
> 
> I simplified to be able to call like this: https://github.com/shenron/vite-demo/blob/master/src/components/DisplayMsgOnce.tsx
> 
> ```ts
> const setup = (p: Props) => {
>   const memo = useMemo();
> 
>   const msgMemo = memo(() => [p.msg]);
> 
>   const msgOnceMemo = memo();
> 
>   return {
>     msgMemo,
>     msgOnceMemo,
>   };
> };
> 
> export default defineComponent({
>   name: 'DisplayMsgOnce',
>   props,
>   setup,
>   render(c: DisplayMsgOnce) {
>     const { msgMemo, msgOnceMemo } = c;
> 
>     return (
>       <ul>
>         <li><small>v-once:</small> {msgOnceMemo(<span>{c.msg}</span>)}</li>
>         <li><small>v-memo:</small> {msgMemo(<span>{c.msg}</span>)}</li>
>       </ul>
>     );
>   },
> });
> ```

`v-once` dose not use `withMemo` under the hood

**Comment by zhiyuanzmj** [comment]
Now, [@vue-macros/jsx-directive@0.4.0](https://vue-macros.sxzz.moe/features/jsx-directive.html) support `v-memo` & `v-once` directive.

``` tsx
// v-memo
<div
  v-for={i in list}
  v-memo={[selected === i]}
  key={i}
  onClick={() => (selected = i)}
>
  {i}: {selected}
</div>

// v-once
<div v-once>{selected}</div>
```
