### ISSUE TITLE
vue3 tsx can not find global component when use camel case.

### ISSUE THREAD

**Issue by WormGirl** [vuejs/babel-plugin-jsx#546]
### 🧐 Problem Description
`PageContainer` is register in global, when use componnet with tsx, camel case not find, but kebab-case work fine, why?  If i import it in file, camel case also work.

### 💻 Sample code

```tsx
import { defineComponent } from "vue";

//  This can not find
export default defineComponent({
  name: 'FormList',
  setup () {
    return () => (
      <PageContainer>
        <template>
        </template>
      </PageContainer>
    );
  }
});
```

```tsx
import { defineComponent } from "vue";

//  This work fine
export default defineComponent({
  name: 'FormList',
  setup () {
    return () => (
      <page-container>
        <template>
        </template>
      </page-container>
    );
  }
});
```

```tsx
import { defineComponent } from "vue";
import PageContainer from '@common/components/Page/PageContainer';

//  This also work fine
export default defineComponent({
  name: 'FormList',
  setup () {
    return () => (
      <PageContainer>
        <template>
        </template>
      </PageContainer>
    );
  }
});
```

### 🚑 Other information
![image](https://user-images.githubusercontent.com/16078260/155690654-649bac3a-a668-45cc-ace5-d9e77d0c5ef8.png)
![image](https://user-images.githubusercontent.com/16078260/155690743-cfd8afb3-44fb-4046-99b6-f668a3398f2a.png)
![image](https://user-images.githubusercontent.com/16078260/155691786-17dc290d-5d8b-423e-a3aa-2a1ed314bde5.png)

**Comment by funny-family** [comment]
@WormGirl, unfortunately as I know you cannot use global component with jsx.

**Comment by WormGirl** [comment]
> @WormGirl, unfortunately as I know you cannot use global component with jsx, because you work with pure js/ts (wihtout vue`s templates).

But i import the component in file  an use with  camel case, this work fine.

**Comment by funny-family** [comment]
> > @WormGirl, unfortunately as I know you cannot use global component with jsx, because you work with pure js/ts (wihtout vue`s templates).
> 
> But i import the component in file and use with camel case, this work fine.

On your [pic](https://user-images.githubusercontent.com/16078260/155690654-649bac3a-a668-45cc-ace5-d9e77d0c5ef8.png) I see no other imports but only "vue". And yes of course it will work if you import component and use it inside other component.

**Comment by funny-family** [comment]
I believe that using a global component/components in your application is always bad, whether you use vue with a template or jsx/tsx.

**Comment by b2nil** [comment]
If it is certain that `PageContainer` has already been registered as a global component, you can utilize the `resolveComponent` function provided by `vue` to resolve it into a vue component instance first and then use it as you wish:
```ts
const PageContainer = resolveComponent("page-container")
return () => (
    <PageContainer>
        <template></template>
    </PageContainer>
)
```

**Comment by abearxiong** [comment]
ts的规范，大写开头的都是函数组件，没引入就找不到吧，ts里面应该需要配置一下

**Comment by sxzz** [comment]
It's not relate to Vue JSX plugin. Try to add global components to dts file.
```ts
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
  }
}
```
