### ISSUE TITLE
【ssr】Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by yanstars** [vuejs/babel-plugin-jsx#568]
### Version
3.2.31

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/nuxt-starter-vvkmga)

### Steps to reproduce
npm run dev 

### What is expected?
no errors

### What is actually happening?
runtime-core.esm-bundler.js:4043 Hydration completed but contains mismatches.

---
【nuxt3】  https://github.com/nuxt/nuxt.js/issues/12998

![image](https://user-images.githubusercontent.com/49805955/157614954-429af668-f349-4aa3-8f25-03ebad6b931e.png)

**Comment by yyx990803** [comment]
Transferred to `vuejs/babel-plugin-jsx` because this is a JSX transform issue.

**Comment by cdwmhcc** [comment]
any update?

**Comment by mcataciertocom** [comment]
Same here but only when use a reverse proxy

**Comment by ZermattChris** [comment]
I'm also getting this using a Vue component in an Astro project. If I change the Astro hydration from "client:idle" to "client:only" then the error goes away. Not sure if I'm doing something wrong, of if it's an issue with Vue or Astro...

Browser Console: Error "Hydration completed but contains mismatches."

**Comment by ElYaiko** [comment]
Still happening, tried with Nuxt (3.11.1).

**Comment by sxzz** [comment]
Track to https://github.com/vuejs/core/issues/11012 https://github.com/vuejs/core/issues/7285
