### ISSUE TITLE
[Question] Hope this plugin can provide a `swc` version.

### ISSUE THREAD

**Issue by Edge00** [vuejs/babel-plugin-jsx#570]
### 🧐 Problem Description
I am using `swc-loader` to make compile quikcker and it works really nice, about 50% quicker 🚀
However if a `.vue` file was written in `tsx`, `swc-loader` can't handle it.
And i notice that `babel` works well because this plugin: [@vue/babel-plugin-jsx](https://github.com/vuejs/babel-plugin-jsx).
Hope this plugin can provide a `swc` version to imporve huge project dev experience.

### 🚑 Other information
https://github.com/swc-project/swc/discussions/3540

**Comment by KayneWang** [comment]
@Edge00 U can try this repo: [vue-jsx-runtime](https://github.com/dolymood/vue-jsx-runtime)

**Comment by sxzz** [comment]
Try https://github.com/g-plane/swc-plugin-vue-jsx
