### ISSUE TITLE
[Question] Help how to use jsx in app.vue?

### ISSUE THREAD

**Issue by social-uni** [vuejs/babel-plugin-jsx#574]
how to use jsx in app.vue?

```
//app.vue
<script lang="tsx">
import {RouterLink, RouterView} from 'vue-router'
import {render} from "vue";

render(
    <div>123</div>
)
</script>
```

i get error  TS2554: Expected 2-3 arguments, but got 1.

![64aed962e53a26d7ebbb9990dc71939](https://user-images.githubusercontent.com/14007972/172017735-b51c8260-ee30-42ce-b879-f6b3373bb69f.png)

**Comment by funny-family** [comment]
@social-uni, try to use [`defineComponent`](https://vuejs.org/api/general.html#definecomponent).

```js
const Foo = defineComponent({
  render() {
    return () => (
      <div>123</div>
    );
  },
});
```
