### ISSUE TITLE
[Question] Help 短横线插槽名称如何转换成jsx插槽函数名？

### ISSUE THREAD

**Issue by wilikeit** [vuejs/babel-plugin-jsx#586]
### 🧐 Problem Description
短横线插槽名称在jsx中转换成驼峰写法，无法成功解析插槽

### 💻 Sample code

 

子组件 Child.vue

  \<div\>我是子组件,下面是父组件的插槽内容：\</div\>
  \<slot name="my-title"  \>\</slot\>

父组件 ：
` 下面写成 myTitle，无法成功解析插槽`

        <Child
          v-slots={{
            myTitle:()=> <div>mytitle插槽</div>
          }}
        />

**Comment by funny-family** [comment]
@wilikeit, did you try this ?
```js
<Child
  v-slots={{
    ['my-title']:()=> <div>mytitle插槽</div>
  }}
/>
```

**Comment by wilikeit** [comment]
> @wilikeit, did you try this ?
> 
> ```js
> <Child
>   v-slots={{
>     'my-title': ()=> <div>mytitle插槽</div>
>   }}
> />
> ```
Good job!
万万没想到直接打个 引号就行,我老是想着转换成驼峰法，思路狭隘了
