### ISSUE TITLE
[Question] How can I use JSX with script setup? 

### ISSUE THREAD

**Issue by nazar1ua** [vuejs/babel-plugin-jsx#595]

**Comment by nazar1ua** [comment]
[The only way?](https://stackoverflow.com/questions/67918363/how-to-use-render-function-in-script-setup-vue3)

**Comment by funny-family** [comment]
> [The only way?](https://stackoverflow.com/questions/67918363/how-to-use-render-function-in-script-setup-vue3)

@nazar1ua, yes and in jsx/tsx files.

**Comment by nazar1ua** [comment]
Okay, thanks
