### ISSUE TITLE
Passing an array to my custom directive in JSX gets a string instead

### ISSUE THREAD

**Issue by ParadiseWitch** [vuejs/babel-plugin-jsx#601]
### Vue version

^3.2.6

### Link to minimal reproduction

https://github.com/ParadiseWitch/vue-jsx-directive-test-demo

### Steps to reproduce

1. Clone.
2. npm i
3. npm run dev, then you can see the output in the console.

### What is expected?

if i use directive like this:
```html 
<div v-permission={['user']}>test1</div>
```
The binding value I want to get is a ArrayLike.

### What is actually happening?

Actually I get a string. 
See the screenshot:

![B LC`)LV%7T8CIPUPE R3V2](https://user-images.githubusercontent.com/37146904/192077824-de71172c-8b5b-40ca-9108-9d5b5d804672.jpg)

![`C4$INU0(UF`FF4~ HP3 JY](https://user-images.githubusercontent.com/37146904/192077825-0a8a24c9-7750-4c89-9086-e0cdeef24754.jpg)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 15.67 GB / 31.93 GB
  Binaries:
    Node: 14.15.1 - D:\nodejs\node.EXE
    Yarn: 1.22.10 - D:\nodejs\node-global\yarn.CMD
    npm: 6.14.8 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vue: ^3.2.6 => 3.2.39
```

**Comment by funny-family** [comment]
@ParadiseWitch  You cannot get `binding` as array and there is no point in it.
