### ISSUE TITLE
使用自定义props接口, 无法在组件内正常通过props.xxx取到值的问题

### ISSUE THREAD

**Issue by wylyzyk** [vuejs/babel-plugin-jsx#607]
### 🧐 Problem Description
通过使用 interface 定义的 props 类型, 在组件中无法按照正常的 *props.xxx* 方式进行读取, 但是在IDE中类型提示都是完整通过的. 并且在 element 中可以看到 props 是作为属性传递了过去, 这样的话可以通过 *attrs.xxx* 方式读取, 但是类型提示不会通过, 并且违背常理

### 💻 Sample code
![image](https://user-images.githubusercontent.com/49738226/195749856-dfa21725-77d6-452f-abb0-665c50b6b144.png)
通过 *props.xxx* 无法读取, 但可以通过 *attrs.xxx* 正常拿到

实际 props 传递过去, 以属性的方式进行展示
![image](https://user-images.githubusercontent.com/49738226/195750563-78bd6c48-c439-4362-9e6d-6f7712bc821c.png)

官方源码中有对这种使用方式的定义
### 💻 Sample code
![image](https://user-images.githubusercontent.com/49738226/195750735-cb9297a8-f855-4433-a4f8-8aa7b8e259ea.png)

### 🚑 Other information
并且 [defineProps](https://cn.vuejs.org/api/sfc-script-setup.html#defineprops-defineemits) 只能在 `<script setup></script>` 中使用, 我不知道有没有其他办法 在传递函数作为参数的同时能使用 *props.xxx* 正常进行调用

**Comment by funny-family** [comment]
@wylyzyk, you did not add `props` object to your component.

**Comment by wylyzyk** [comment]
> @wylyzyk, you did not add `props` object to your component.

But when I pass the `function` as the parameter of *defineComponent*, I cannot add props `object`

**Comment by funny-family** [comment]
@wylyzyk, try this instead
```js
const Bar = defineComponent({
  props: {
    type: String,
    required: true,
  },
  setup(props) {
    return () => <h1>{props.foo}</h1>
  },
});

```

**Comment by wylyzyk** [comment]
@funny-family , I now use the following methods, It can work normally. There is no problem for the time being
```typescript
interface IProps {
  foo: string;
}

const Bar = defineComponent((props) => {
  return () => <h1>{props.foo}</h1>
});

Bar.props = {
  foo: "foo"
} as IProps;
```

**Comment by funny-family** [comment]
@wylyzyk, I forgot about this one. Nice solution.
