### ISSUE TITLE
This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". 

### ISSUE THREAD

**Issue by Pancake-Q** [vuejs/babel-plugin-jsx#643]
### 💻 Sample code
```js
module.exports = {
    presets: ['@vue/cli-plugin-babel/preset'],
    plugins: ['@vue/babel-plugin-jsx'],
}
```
已经配置了bable之前没有问题最近出现了这个是怎么回事呢

**Comment by Pancake-Q** [comment]
执行了npm update 之后出现的这个问题，不确定是那一部分出现了不兼容

**Comment by lysilver** [comment]
> 执行了npm update 之后出现的这个问题，不确定是那一部分出现了不兼容

<script lang="jsx">

**Comment by sxzz** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required
