### ISSUE TITLE
[Question] Help

### ISSUE THREAD

**Issue by RexHung0302** [vuejs/babel-plugin-jsx#645]
### 🧐 Problem Description

I installed babel-plugin-jsx and set it in .eslintrc.js, first render was fine, but when I save the IDE and reload it, then compiler will show the error.

`[eslint] Failed to load plugin '@vue/babel-plugin-jsx' declared in '.eslintrc.js': Cannot find module '@vue/eslint-plugin-babel-plugin-jsx'`

<img width="546" alt="截圖 2023-05-31 上午11 20 03" src="https://github.com/vuejs/babel-plugin-jsx/assets/45451039/c0e5ca37-0f3c-4113-acea-9d2c8261ba3d">

### 💻 Sample code

this is my .eslintrc.js
```js
module.exports = {
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 2020,
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
  },
  root: true,
  env: {
    node: true,
  },
  extends: ['eslint:recommended', 'plugin:vue/vue3-recommended', 'eslint:recommended', '@vue/typescript/recommended', '@vue/prettier', '@vue/prettier/@typescript-eslint'],
  plugins: ['@vue/babel-plugin-jsx'],
  rules: {
    'vue/script-setup-uses-vars': 'off',
    'prettier/prettier': 'off',
    'no-unused-vars': 'off',
    'vue/component-definition-name-casing': ['error', 'kebab-case'],
    '@typescript-eslint/ban-ts-ignore': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};
```

I only installed babel-plugin-jsx, and I try to install `@vue/eslint-plugin-babel-plugin-jsx` was failed.

**Comment by funny-family** [comment]
@RexHung0302, remove it `plugins: ['@vue/babel-plugin-jsx'],` from linter config file.

**Comment by RexHung0302** [comment]
@funny-family Thank u, I remove that and add `plugins: ['@vue/babel-plugin-jsx']` at babel.config.js, it works.

Thank u for reply again.
