### ISSUE TITLE
[BUG] Report bug 在最新的1.1.2版本中dist文件夹不存在

### ISSUE THREAD

**Issue by censujiang** [vuejs/babel-plugin-jsx#647]
模块找不到 `@vue/babel-plugin-jsx` 的dist文件夹，检查npm后发现在1.1.1版本后的1.1.2版本中，dist文件夹忘了提交npm了

哥们，打包的时候好歹注意一下，我差点以为供应链投毒了... @sxzz

**Comment by sxzz** [comment]
Sorry, please try `@vue/babel-plugin-jsx@1.1.3`
