### ISSUE TITLE
[BUG] empty string transform to true

### ISSUE THREAD

**Issue by wyt930927** [vuejs/babel-plugin-jsx#658]
### 🐛 Bug description

` <Field label="" />`
`
_createVNode(Field, {
"label": true
})
`

### 🏞 Desired result

_createVNode(Field, {
"label":""
})

### 🚑 Other information
Based on the content of the link below, we understand that this issue has been resolved in @vue/babel-plugin-jsx@v1.1.5. We need to upgrade  @vue/babel-plugin-jsx version from 1.1.1 to 1.1.5
https://github.com/vuejs/babel-plugin-jsx/commit/a030d15018ca348d0be24d47b6759ea81c668b20

**Comment by wyt930927** [comment]
> 

Can ignore this issue.

**Comment by sxzz** [comment]
relate #653
