### ISSUE TITLE
Can this plugin be used in a browser?

### ISSUE THREAD

**Issue by Devmond** [vuejs/babel-plugin-jsx#672]
### 🧐 Problem Description

There are two questions in the closed issue list asking about how this plugin could be used in a browser, both unfortunately have the same curt response. Can you please state clearly on the read me page whether this plugin is usable in a browser or not? 

I have exported a bundle via browserify but the code below doesn't work, it complains about not recognizing the vue plugin.

### 💻 Sample code

let jsxCode = Babel.transform("<b></b>", {"presets": ["@vue/babel-plugin-jsx"]}).code;

**Comment by sxzz** [comment]
Sure.
https://github.com/sxzz/vue-jsx-playground/blob/main/src/components/jsx-editor.vue#L42-L43
