### ISSUE TITLE
vModel 修饰符不能动态

### ISSUE THREAD

**Issue by luocong2016** [vuejs/babel-plugin-jsx#679]
### 🐛 Bug description
```
 v-model={[dataRef.value, 'value']}
````

### 📝 Steps to reproduce

v-model argumens 无法动态，如静态变量承接都会引起 update:XX 函数是 undefined

### 🏞 Desired result

```
const xx = 'value'
 v-model={[dataRef.value, xx]}
````

**Comment by zhiyuanzmj** [comment]
#642

**Comment by zhiyuanzmj** [comment]
## [vue-macros](https://vue-macros.dev/features/jsx-directive.html#dynamic-arguments) already supports dynamic argument

<img width="725" alt="image" src="https://github.com/vuejs/babel-plugin-jsx/assets/32807958/4f6b7dc3-b7f3-41a1-8f4f-6d9fd23d5f2e">
