### ISSUE TITLE
[BUG] {} 渲染异常

### ISSUE THREAD

**Issue by wanchun** [vuejs/babel-plugin-jsx#682]
### 🐛 Bug description

组件：
```
import { defineComponent } from 'vue'


export default defineComponent({
    props: {
        title: String
    },
    setup(props){
        return ()=>{
            return <div>{props.title}</div>
        }
    }
})
```

当传入的title从对象变成字符串，就会报错
```
const title = ref({a: 1})

setTimeout(() => {
  title.value = 1;
}, 1000);

```

### 📝 Steps to reproduce

Reproduction Link (required): 

https://github.com/wanchun/jsx-bug

### 🏞 Desired result

![企业微信截图_2f97ab77-0ddd-499c-9812-e462b316d909](https://github.com/vuejs/babel-plugin-jsx/assets/4636302/472cb8a7-d1ff-46f2-a8d2-289b95fbfa76)

**Comment by sxzz** [comment]
在JSX中，不能直接渲染一个对象，不会转换为 JSON。
