### ISSUE TITLE
[Question] Help配置列表

### ISSUE THREAD

**Issue by Samele-QoQ** [vuejs/babel-plugin-jsx#699]
看着你给了一个引入，还有对应参数的意思以及默认值。
我想问，怎么定制化配置呀，这方面了解不是太深。
求解惑或者完善一下您的文档

谢谢！

**Comment by sxzz** [comment]
取决于你怎么使用 Babel 插件。如果是 Vite 插件，参见 https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx#vitejsplugin-vue-jsx-

如果是直接使用 Babel，参见 https://babeljs.io/docs/plugins#plugin-options
