### ISSUE TITLE
[BUG] Report bug

### ISSUE THREAD

**Issue by hnustwjj** [vuejs/babel-plugin-jsx#704]
### 🐛 Bug description

failed to view [https://vue-jsx-explorer.netlify.app/](https://vue-jsx-explorer.netlify.app/)

### 📝 Steps to reproduce

![image](https://github.com/vuejs/babel-plugin-jsx/assets/78677609/4c38b1d6-85d6-4576-bb55-925c1cdf8d9c)

Reproduction Link (required): https://vue-jsx-explorer.netlify.app/

**Comment by sxzz** [comment]
Fixed via 3852069f002bd8aa521d69122c958e1df65fe042
