### ISSUE TITLE
[Question] how to make vue jsx ast return to jsx

### ISSUE THREAD

**Issue by hnustwjj** [vuejs/babel-plugin-jsx#705]
### 🧐 Problem Description

I want to make some changes to the vue jsx code through babel. I want to know whether the ast of vue jsx can be converted back to jsx. Or can you provide me with some ideas?

![image](https://github.com/vuejs/babel-plugin-jsx/assets/78677609/058af738-047e-4935-9a68-9e9562a9dec1)

**Comment by sxzz** [comment]
Vue JSX syntax is standard JSX syntax. Therefore, you can use general toolchains.

For example, you can use `@babel/parser` and `@babel/generator` to parse the AST and generate code.
