### ISSUE TITLE
[Question] How to set a Symbolic Link in README.md

### ISSUE THREAD

**Issue by showlotus** [vuejs/babel-plugin-jsx#706]
### 🧐 Problem Description

![image](https://github.com/vuejs/babel-plugin-jsx/assets/56748472/8d1720c6-9ae1-4a45-ab06-b3e757e1272c)
I has written the Symbolic Link like this in my README.md. 
![image](https://github.com/vuejs/babel-plugin-jsx/assets/56748472/7346b57c-b2ed-4d6f-b5cb-a8d678dd1c15)
But it doesn't work. Is there any other configuration required?
![image](https://github.com/vuejs/babel-plugin-jsx/assets/56748472/7dbed34d-4d68-4ee5-9af7-453af4d0a17a)

**Comment by sxzz** [comment]
On UNIX-like System, run
```
ln -s packages/babel-plugin-jsx/README.md README.md
```

**Comment by showlotus** [comment]
> On UNIX-like System, run
> 
> ```
> ln -s packages/babel-plugin-jsx/README.md README.md
> ```

Thank you !
