### ISSUE TITLE
The inline style setting failed

### ISSUE THREAD

**Issue by Sharang-heng** [vuejs/babel-plugin-jsx#710]
### 🐛 Bug description
Set the inline style to the div
![image](https://github.com/vuejs/babel-plugin-jsx/assets/69613396/4a2404b2-6c0e-456f-9872-e7616c91aec6)
padding、margin、fontSize are missing
![image](https://github.com/vuejs/babel-plugin-jsx/assets/69613396/e909a630-8793-4366-84b6-5f7152ab3edd)
but when I set padding:0，is success
![image](https://github.com/vuejs/babel-plugin-jsx/assets/69613396/c7832846-5934-4b51-867e-e0f226ddaed1)

### address
https://github.com/Sharang-heng/vue3-issue

**Comment by sxzz** [comment]
https://github.com/vuejs/core/issues/10994#issuecomment-2126222519
